name: $(GitVersion.SemVer)
resources:
- repo: self
  fetchDepth: 15

trigger:
  - master

queue:
  name: Hosted VS2017
steps:
- task: gittools.gitversion.gitversion-task.GitVersion@4
  displayName: GitVersion
  inputs:
    preferBundledVersion: false

- powershell: .\build.ps1 -task test
  displayName: 'Build and Test module'
  workingDirectory: $(System.DefaultWorkingDirectory)
  condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/master'))

- powershell: .\build.ps1 -task publish
  displayName: 'Build, Test, and Publish module'
  workingDirectory: $(System.DefaultWorkingDirectory)
  env:
    NugetApiKey: $(NugetApiKey)
    GithubToken: $(GithubToken)
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

- task: PublishTestResults@2
  displayName: 'Publish Test Results **/PesterResult.XML'
  inputs:
    testResultsFormat: NUnit
    testResultsFiles: '**/PesterResult.XML'
  condition: succeededOrFailed()

- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage from $(System.DefaultWorkingDirectory)\tests.XML'
  inputs:
    summaryFileLocation: '$(System.DefaultWorkingDirectory)\PesterCoverage.XML'
  condition: succeededOrFailed()
